# Dependencies
markdown:         kramdown
highlighter:      rouge

# Setup
title:            'Code And Coffee'
tagline:          'Blog'
description:      'A place to share my mistakes (and their solutions) with the {hello} world!'
url:              http://codecoffee.org
baseurl:          '/'
                  # the optional subpath of your site, e.g. "/blog"
                  # NB: This applies to all pages in your Jekyll site.
                  # If you want to move just the blog index pages but keep
                  # other pages at root, see the paginate_path and
                  # sidebar_blog_link below.

author:
  name:           'M-Barrows'

paginate:         5
paginate_path:    '/blog/page:num'
                    # Or '/blog/page:num' if you want to move your index pages

plugins:
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate

# Sidebar link settings
sidebar_home_link:  true
sidebar_blog_link:  '/blog'   # By default, your home page is your blog
                                # page. If you change your paginate_path,
                                # set this to the root of the paginate_path
                                # to enable a separate blog link.

remote_theme: fongandrew/hydeout

repo: https://github.com/M-Barrows/
linkedin: https://www.linkedin.com/in/michaelabarrows/
mastodon: https://hachyderm.io/@CodeAndCoffee

defaults:
  - scope:
      path: "assets/img"
    values:
      image: true