name: Deploy to Docker Hub

on:
  push:
    branches: [ "gh-pages" ]
  pull_request:
    branches: [ "gh-pages" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        uses: actions/jekyll-build-pages@v1
        with:
          destination: "./_site"
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3
        with:
          name: codecoffee_site
          path: |
            _site
            Dockerfile
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download _site dir
      uses: actions/download-artifact@v3
      with:
        name: codecoffee_site
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: codecoffee/blog:latest
        context: .
